# t=()
# print("empty tuple" , t)
t=({"name1", 23, "denmar"}, {"name2", 24, "tomy"})
t1=(("name21", 23, "denmar"), ("name22", 24, "tomy"))
print(t)
print(t1)
print(type(t1))
print(type(t))
f=("grapes", "apple")
print(f)
f.append("banna")
print(f)
